import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
    build: {
        rollupOptions: {
            input: {
                main: resolve(__dirname, 'index.html'),
                privacyPolicy: resolve(__dirname, 'privacy-policy/index.html'),
                cookieClicker: resolve(__dirname, 'cookie-clicker.html'),
                cookieClicker2: resolve(__dirname, 'cookie-clicker-2.html'),
                funClicker: resolve(__dirname, 'fun-clicker.html'),
                liquorClicker: resolve(__dirname, 'liquor-clicker.html'),
                bloodmoney: resolve(__dirname, 'bloodmoney.html'),
                italianBrainrotBabyClicker: resolve(__dirname, 'italian-brainrot-baby-clicker.html'),
                clickerEvolutionPuzzle2: resolve(__dirname, 'clicker-evolution-puzzle-2.html'),
                mineClickerCookie: resolve(__dirname, 'mine-clicker-cookie.html'),
                loafClicker: resolve(__dirname, 'loaf-clicker.html'),
                brainrotClicker: resolve(__dirname, 'brainrot-clicker.html'),
                hackingHero: resolve(__dirname, 'hacking-hero.html'),
                icebreakersIdleClicker: resolve(__dirname, 'icebreakers-idle-clicker.html'),
                idleLandmarkBuilder: resolve(__dirname, 'idle-landmark-builder.html'),
                ageWarsIdle: resolve(__dirname, 'age-wars-idle.html'),
                tinyFishing: resolve(__dirname, 'tiny-fishing.html'),
                woodmanIdleTycoon: resolve(__dirname, 'woodman-idle-tycoon.html'),
                tankMastersIdleTanks: resolve(__dirname, 'tank-masters-idle-tanks.html'),
                flipSkaterIdle: resolve(__dirname, 'flip-skater-idle.html'),
                growSlime: resolve(__dirname, 'grow-slime.html'),
                idleGameDevSimulator: resolve(__dirname, 'idle-game-dev-simulator.html'),
                paperIo2: resolve(__dirname, 'paper-io-2.html'),
                battletabs: resolve(__dirname, 'battletabs.html'),
                twoVTwoIo: resolve(__dirname, '2v2-io.html'),
                edelweiss: resolve(__dirname, 'edelweiss.html'),
                crazyCattle3D: resolve(__dirname, 'crazy-cattle-3d.html'),
                blockBlast: resolve(__dirname, 'block-blast.html'),
                googleDino: resolve(__dirname, 'google-dino.html'),
                basketballStars: resolve(__dirname, 'basketball-stars.html'),
                lolshotIo: resolve(__dirname, 'lolshot-io.html'),
                splatoonIo: resolve(__dirname, 'splatoon-io.html'),
                adventureCapitalist: resolve(__dirname, 'adventure-capitalist.html'),
                idleBreakout: resolve(__dirname, 'idle-breakout.html'),
                dogeMiner: resolve(__dirname, 'doge-miner.html'),
                clickerHeroes: resolve(__dirname, 'clicker-heroes.html'),
                notFound: resolve(__dirname, '404/index.html'),
                arcade: resolve(__dirname, 'arcade.games/index.html'),
                clicker: resolve(__dirname, 'clicker.games/index.html'),
                idle: resolve(__dirname, 'idle.games/index.html'),
                io: resolve(__dirname, 'io.games/index.html'),
                adventure: resolve(__dirname, 'adventure.games/index.html'),
                sports: resolve(__dirname, 'sports.games/index.html'),
                newGames: resolve(__dirname, 'new.games/index.html'),
                search: resolve(__dirname, 'search/index.html'),
                aboutUs: resolve(__dirname, 'about-us/index.html'),
                contactUs: resolve(__dirname, 'contact-us/index.html'),
                dmca: resolve(__dirname, 'dmca/index.html'),
                terms: resolve(__dirname, 'terms-of-service/index.html'),
            },
        },
    },
});
