/**
 * Central list of games for search and sidebars.
 * Add new games here; keep name, url, category, image, addedDate in sync.
 * addedDate: used for "New Games" sidebars (Arcade / .io / Adventure / Sports), newest first.
 */
export const GAMES = [
    {
        name: 'Cookie Clicker',
        url: '/cookie-clicker.html',
        category: 'Clicker',
        categories: ['Clicker', 'Idle'],
        image: '/assets/cookie-clicker.png',
        addedDate: '2026-01-15',
    },
    {
        name: 'Cookie Clicker 2',
        url: '/cookie-clicker-2.html',
        category: 'Clicker',
        categories: ['Clicker', 'Idle'],
        image: '/assets/cookie-clicker-2.png',
        addedDate: '2026-02-01',
    },
    {
        name: 'Fun Clicker',
        url: '/fun-clicker.html',
        category: 'Clicker',
        categories: ['Clicker', 'Idle', 'Arcade'],
        image: '/assets/fun-clicker.png',
        addedDate: '2026-02-19',
    },
    {
        name: 'Liquor Clicker',
        url: '/liquor-clicker.html',
        category: 'Clicker',
        categories: ['Clicker', 'Idle'],
        image: '/assets/liquor-clicker.png',
        addedDate: '2026-02-20',
    },
    {
        name: 'BLOODMONEY',
        url: '/bloodmoney.html',
        category: 'Clicker',
        categories: ['Clicker', 'Arcade'],
        image: '/assets/bloodmoney.png',
        addedDate: '2026-02-21',
    },
    {
        name: 'Italian Brainrot Baby Clicker',
        url: '/italian-brainrot-baby-clicker.html',
        category: 'Clicker',
        categories: ['Clicker', 'Idle'],
        image: '/assets/italian-brainrot-baby-clicker.png',
        addedDate: '2026-02-22',
    },
    {
        name: 'Clicker Evolution Puzzle 2',
        url: '/clicker-evolution-puzzle-2.html',
        category: 'Clicker',
        categories: ['Clicker'],
        image: '/assets/clicker-evolution-puzzle-2.png',
        addedDate: '2026-02-23',
    },
    {
        name: 'Mine Clicker: Cookie!',
        url: '/mine-clicker-cookie.html',
        category: 'Clicker',
        categories: ['Clicker'],
        image: '/assets/mine-clicker-cookie.png',
        addedDate: '2026-02-24',
    },
    {
        name: 'Loaf Clicker',
        url: '/loaf-clicker.html',
        category: 'Clicker',
        categories: ['Clicker'],
        image: '/assets/loaf-clicker.png',
        addedDate: '2026-02-25',
    },
    {
        name: 'Brainrot Clicker',
        url: '/brainrot-clicker.html',
        category: 'Clicker',
        categories: ['Clicker'],
        image: '/assets/brainrot-clicker.png',
        addedDate: '2026-02-26',
    },
    {
        name: 'Hacking Hero: Hacker Clicker',
        url: '/hacking-hero.html',
        category: 'Clicker',
        categories: ['Clicker'],
        image: '/assets/hacking-hero.png',
        addedDate: '2026-02-27',
    },
    {
        name: 'Icebreakers: Idle Clicker',
        url: '/icebreakers-idle-clicker.html',
        category: 'Idle',
        categories: ['Idle', 'Clicker'],
        image: '/assets/icebreakers-idle-clicker.png',
        addedDate: '2026-02-28',
    },
    {
        name: 'Idle Landmark Builder',
        url: '/idle-landmark-builder.html',
        category: 'Idle',
        categories: ['Idle'],
        image: '/assets/idle-landmark-builder.png',
        addedDate: '2026-02-29',
    },
    {
        name: 'Tiny Fishing',
        url: '/tiny-fishing.html',
        category: 'Arcade',
        categories: ['Arcade', 'Idle'],
        image: '/assets/tiny-fishing.png',
        addedDate: '2026-03-01',
    },
    {
        name: 'Age Wars Idle',
        url: '/age-wars-idle.html',
        category: 'Idle',
        categories: ['Idle'],
        image: '/assets/age-wars-idle.png',
        addedDate: '2026-03-02',
    },
    {
        name: 'Woodman Idle Tycoon',
        url: '/woodman-idle-tycoon.html',
        category: 'Idle',
        categories: ['Idle'],
        image: '/assets/woodman-idle-tycoon.png',
        addedDate: '2026-03-03',
    },
    {
        name: 'Tank Masters: Idle Tanks',
        url: '/tank-masters-idle-tanks.html',
        category: 'Idle',
        categories: ['Idle', 'Arcade'],
        image: '/assets/tank-masters-idle-tanks.png',
        addedDate: '2026-03-04',
    },
    {
        name: 'Flip Skater Idle',
        url: '/flip-skater-idle.html',
        category: 'Sports',
        categories: ['Sports', 'Idle'],
        image: '/assets/flip-skater-idle.png',
        addedDate: '2026-03-05',
    },
    {
        name: 'Grow Slime',
        url: '/grow-slime.html',
        category: 'Idle',
        categories: ['Idle'],
        image: '/assets/grow-slime.png',
        addedDate: '2026-03-06',
    },
    {
        name: 'Idle Game Dev Simulator',
        url: '/idle-game-dev-simulator.html',
        category: 'Idle',
        categories: ['Idle'],
        image: '/assets/idle-game-dev-simulator.png',
        addedDate: '2026-03-07',
    },
    {
        name: 'Paper.IO 2',
        url: '/paper-io-2.html',
        category: '.io',
        categories: ['.io', 'Arcade'],
        image: '/assets/paper-io-2.png',
        addedDate: '2026-03-08',
    },
    {
        name: 'BattleTabs',
        url: '/battletabs.html',
        category: '.io',
        categories: ['.io', 'Arcade'],
        image: '/assets/battletabs.png',
        addedDate: '2026-03-09',
    },
    {
        name: '2v2.io',
        url: '/2v2-io.html',
        category: '.io',
        categories: ['.io', 'Arcade'],
        image: '/assets/2v2-io.png',
        addedDate: '2026-03-10',
    },
    {
        name: 'Edelweiss',
        url: '/edelweiss.html',
        category: 'Adventure',
        categories: ['Adventure', 'Arcade'],
        image: '/assets/edelweiss.png',
        addedDate: '2026-03-11',
    },
    {
        name: 'Crazy Cattle 3D',
        url: '/crazy-cattle-3d.html',
        category: 'Arcade',
        categories: ['Arcade', 'Adventure'],
        image: '/assets/crazy-cattle-3d.png',
        addedDate: '2026-03-12',
    },
    {
        name: 'Block Blast',
        url: '/block-blast.html',
        category: 'Arcade',
        categories: ['Arcade', 'Puzzle'],
        image: '/assets/block-blast.png',
        addedDate: '2026-03-13',
    },
    {
        name: 'Google Dino',
        url: '/google-dino.html',
        category: 'Arcade',
        categories: ['Arcade', 'Adventure'],
        image: '/assets/google-dino.png',
        addedDate: '2026-03-14',
    },
    {
        name: 'Basketball Stars',
        url: '/basketball-stars.html',
        category: 'Sports',
        categories: ['Sports', 'Arcade'],
        image: '/assets/basketball-stars.png',
        addedDate: '2026-03-15',
    },
    {
        name: 'Doge Miner',
        url: '/doge-miner.html',
        category: 'Clicker',
        categories: ['Clicker', 'Idle'],
        image: '/assets/doge-miner.png',
        addedDate: '2026-03-16',
    },
    {
        name: 'LOLShot.io',
        url: '/lolshot-io.html',
        category: '.io',
        categories: ['.io', 'Arcade', 'Sports'],
        image: '/assets/lolshot-io.png',
        addedDate: '2026-03-17',
    },
    {
        name: 'Splatoon.io',
        url: '/splatoon-io.html',
        category: '.io',
        categories: ['.io', 'Arcade'],
        image: '/assets/splatoon-io.png',
        addedDate: '2026-03-18',
    },
    {
        name: 'Idle Breakout',
        url: '/idle-breakout.html',
        category: 'Idle',
        categories: ['Idle', 'Arcade'],
        image: '/assets/idle-breakout.png',
        addedDate: '2026-03-19',
    },
    {
        name: 'Adventure Capitalist',
        url: '/adventure-capitalist.html',
        category: 'Idle',
        categories: ['Idle', 'Clicker'],
        image: '/assets/adventure-capitalist.png',
        addedDate: '2026-03-20',
    },
    {
        name: 'Clicker Heroes',
        url: '/clicker-heroes.html',
        category: 'Idle',
        categories: ['Idle', 'Clicker', 'Adventure'],
        image: '/assets/clicker-heroes.png',
        addedDate: '2026-03-21',
    },
];
